# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install pipenv packages
      run: pipenv install

    - name: Generate data set
      run: pipenv run python generator.py

    - name: Build the file
      run: pipenv run python build.py build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: |
          web/dist/
          !web/dist/**/*.gitignore
        retention-days: 5

  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: sfo3
        SOURCE_DIR: web/dist/
        AWS_S3_ENDPOINT: 'sfo3.digitaloceanspaces.com'
