name: Deployment
on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install pipenv packages
      run: pipenv install

    - name: Generate data set
      run: pipenv run python generator.py

    - name: Build the file
      run: pipenv run python build.py build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: |
          web/dist/
          !web/dist/**/*.gitignore
        retention-days: 5

  staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - uses: horochx/deploy-via-scp@master
      with:
        local: website/*
        remote: ${{ secrets.PRODUCTION_SCP_REMOTE }}
        host: ${{ secrets.PRODUCTION_SCP_HOST }}
        port: 22 # eg: 22
        user: ${{ secrets.PRODUCTION_SCP_USER }}
        key: ${{ secrets.SCP_KEY }}
